project:
  type: website
  output-dir: docs

website:
  title: "Dian's Blog"
  site-url: https://www.diantwood.github.io
  description: "A blog for Dian"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Diantwood
      - icon: twitter
        href: https://twitter.com/diantwood
format:
  html:
    theme: lux    
    css: styles.css



